# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Subtitle_Adjuster.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winSubtitleAdjuster(object):
    def setupUi(self, winSubtitleAdjuster):
        winSubtitleAdjuster.setObjectName("winSubtitleAdjuster")
        winSubtitleAdjuster.resize(575, 148)
        icon = QtGui.QIcon.fromTheme("C:\\Users\\baris\\Desktop\\Projects\\Subtitle_Adjuster\\icon.ico")
        winSubtitleAdjuster.setWindowIcon(icon)
        self.btnAdjust = QtWidgets.QPushButton(winSubtitleAdjuster)
        self.btnAdjust.setGeometry(QtCore.QRect(250, 110, 75, 23))
        self.btnAdjust.setObjectName("btnAdjust")
        self.cbWhat = QtWidgets.QComboBox(winSubtitleAdjuster)
        self.cbWhat.setGeometry(QtCore.QRect(258, 42, 43, 22))
        self.cbWhat.setObjectName("cbWhat")
        self.cbWhat.addItem("")
        self.cbWhat.addItem("")
        self.cbWhat.addItem("")
        self.cbWhat.addItem("")
        self.lblHowMany = QtWidgets.QLabel(winSubtitleAdjuster)
        self.lblHowMany.setGeometry(QtCore.QRect(180, 74, 75, 22))
        self.lblHowMany.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblHowMany.setObjectName("lblHowMany")
        self.lblWhat = QtWidgets.QLabel(winSubtitleAdjuster)
        self.lblWhat.setGeometry(QtCore.QRect(180, 42, 75, 22))
        self.lblWhat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblWhat.setObjectName("lblWhat")
        self.cbAddSub = QtWidgets.QComboBox(winSubtitleAdjuster)
        self.cbAddSub.setGeometry(QtCore.QRect(330, 75, 43, 22))
        self.cbAddSub.setObjectName("cbAddSub")
        self.cbAddSub.addItem("")
        self.cbAddSub.addItem("")
        self.entHowMany = QtWidgets.QLineEdit(winSubtitleAdjuster)
        self.entHowMany.setGeometry(QtCore.QRect(258, 76, 67, 20))
        self.entHowMany.setObjectName("entHowMany")
        self.entFileName = QtWidgets.QLineEdit(winSubtitleAdjuster)
        self.entFileName.setGeometry(QtCore.QRect(75, 12, 475, 20))
        self.entFileName.setObjectName("entFileName")
        self.lblFileName = QtWidgets.QLabel(winSubtitleAdjuster)
        self.lblFileName.setGeometry(QtCore.QRect(20, 10, 50, 22))
        self.lblFileName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFileName.setObjectName("lblFileName")

        self.retranslateUi(winSubtitleAdjuster)
        QtCore.QMetaObject.connectSlotsByName(winSubtitleAdjuster)

    def retranslateUi(self, winSubtitleAdjuster):
        _translate = QtCore.QCoreApplication.translate
        winSubtitleAdjuster.setWindowTitle(_translate("winSubtitleAdjuster", "Subtitle Adjuster"))
        self.btnAdjust.setText(_translate("winSubtitleAdjuster", "Adjust"))
        self.cbWhat.setItemText(0, _translate("winSubtitleAdjuster", "ms"))
        self.cbWhat.setItemText(1, _translate("winSubtitleAdjuster", "s"))
        self.cbWhat.setItemText(2, _translate("winSubtitleAdjuster", "m"))
        self.cbWhat.setItemText(3, _translate("winSubtitleAdjuster", "h"))
        self.lblHowMany.setText(_translate("winSubtitleAdjuster", "How Many ms:"))
        self.lblWhat.setText(_translate("winSubtitleAdjuster", "What:"))
        self.cbAddSub.setItemText(0, _translate("winSubtitleAdjuster", "+"))
        self.cbAddSub.setItemText(1, _translate("winSubtitleAdjuster", "-"))
        self.lblFileName.setText(_translate("winSubtitleAdjuster", "File Path:"))
