# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Subtitle_Rename.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winSubtitleRename(object):
    def setupUi(self, winSubtitleRename):
        winSubtitleRename.setObjectName("winSubtitleRename")
        winSubtitleRename.resize(657, 396)
        icon = QtGui.QIcon.fromTheme("icon.ico")
        winSubtitleRename.setWindowIcon(icon)
        self.entPath = QtWidgets.QLineEdit(winSubtitleRename)
        self.entPath.setGeometry(QtCore.QRect(102, 30, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.entPath.setFont(font)
        self.entPath.setStyleSheet("background-color: rgba(244,244,244,150);")
        self.entPath.setObjectName("entPath")
        self.btnRenameSub = QtWidgets.QPushButton(winSubtitleRename)
        self.btnRenameSub.setGeometry(QtCore.QRect(134, 330, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnRenameSub.setFont(font)
        self.btnRenameSub.setAutoFillBackground(False)
        self.btnRenameSub.setStyleSheet("color: rgb(255, 221, 117);\n"
"background-color:rgb(60, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.btnRenameSub.setCheckable(False)
        self.btnRenameSub.setChecked(False)
        self.btnRenameSub.setAutoDefault(False)
        self.btnRenameSub.setDefault(False)
        self.btnRenameSub.setFlat(False)
        self.btnRenameSub.setObjectName("btnRenameSub")
        self.lblBackground = QtWidgets.QLabel(winSubtitleRename)
        self.lblBackground.setGeometry(QtCore.QRect(-288, -156, 1013, 801))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBackground.setFont(font)
        self.lblBackground.setText("")
        self.lblBackground.setPixmap(QtGui.QPixmap("background.jpg"))
        self.lblBackground.setScaledContents(True)
        self.lblBackground.setObjectName("lblBackground")
        self.lblFileName = QtWidgets.QLabel(winSubtitleRename)
        self.lblFileName.setGeometry(QtCore.QRect(30, 30, 65, 22))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblFileName.setFont(font)
        self.lblFileName.setStyleSheet("color: rgb(255, 221, 117);\n"
"")
        self.lblFileName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFileName.setObjectName("lblFileName")
        self.btnDelete = QtWidgets.QPushButton(winSubtitleRename)
        self.btnDelete.setGeometry(QtCore.QRect(288, 330, 133, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelete.setFont(font)
        self.btnDelete.setAutoFillBackground(False)
        self.btnDelete.setStyleSheet("color: rgb(255, 221, 117);\n"
"background-color:rgb(60, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.btnDelete.setCheckable(False)
        self.btnDelete.setChecked(False)
        self.btnDelete.setAutoDefault(False)
        self.btnDelete.setDefault(False)
        self.btnDelete.setFlat(False)
        self.btnDelete.setObjectName("btnDelete")
        self.entEpisodes = QtWidgets.QTextEdit(winSubtitleRename)
        self.entEpisodes.setGeometry(QtCore.QRect(104, 82, 473, 239))
        self.entEpisodes.setStyleSheet("background-color: rgba(244,244,244,150);")
        self.entEpisodes.setObjectName("entEpisodes")
        self.lblEpisodes = QtWidgets.QLabel(winSubtitleRename)
        self.lblEpisodes.setGeometry(QtCore.QRect(26, 88, 65, 22))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEpisodes.setFont(font)
        self.lblEpisodes.setStyleSheet("color: rgb(255, 221, 117);\n"
"")
        self.lblEpisodes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblEpisodes.setObjectName("lblEpisodes")
        self.btnRenameEpisodes = QtWidgets.QPushButton(winSubtitleRename)
        self.btnRenameEpisodes.setGeometry(QtCore.QRect(438, 330, 117, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnRenameEpisodes.setFont(font)
        self.btnRenameEpisodes.setAutoFillBackground(False)
        self.btnRenameEpisodes.setStyleSheet("color: rgb(255, 221, 117);\n"
"background-color:rgb(60, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.btnRenameEpisodes.setCheckable(False)
        self.btnRenameEpisodes.setChecked(False)
        self.btnRenameEpisodes.setAutoDefault(False)
        self.btnRenameEpisodes.setDefault(False)
        self.btnRenameEpisodes.setFlat(False)
        self.btnRenameEpisodes.setObjectName("btnRenameEpisodes")
        self.toolPath = QtWidgets.QToolButton(winSubtitleRename)
        self.toolPath.setGeometry(QtCore.QRect(546, 30, 27, 21))
        self.toolPath.setStyleSheet("background-color: rgba(244,244,244,150);")
        self.toolPath.setObjectName("toolPath")
        self.lblBackground.raise_()
        self.entPath.raise_()
        self.btnRenameSub.raise_()
        self.lblFileName.raise_()
        self.btnDelete.raise_()
        self.entEpisodes.raise_()
        self.lblEpisodes.raise_()
        self.btnRenameEpisodes.raise_()
        self.toolPath.raise_()

        self.retranslateUi(winSubtitleRename)
        QtCore.QMetaObject.connectSlotsByName(winSubtitleRename)

    def retranslateUi(self, winSubtitleRename):
        _translate = QtCore.QCoreApplication.translate
        winSubtitleRename.setWindowTitle(_translate("winSubtitleRename", "Subtitle Rename Program"))
        self.btnRenameSub.setText(_translate("winSubtitleRename", "Rename Subtitles"))
        self.lblFileName.setText(_translate("winSubtitleRename", "File Path:"))
        self.btnDelete.setText(_translate("winSubtitleRename", "Delete Extra Folders"))
        self.lblEpisodes.setText(_translate("winSubtitleRename", "Episodes:"))
        self.btnRenameEpisodes.setText(_translate("winSubtitleRename", "Rename Episodes"))
        self.toolPath.setText(_translate("winSubtitleRename", "..."))
